<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Hackathon-Demo" duration-ms="48979" started-at="2018-10-25T09:52:53Z" finished-at="2018-10-25T09:53:42Z">
    <groups>
    </groups>
    <test name="Write new post" duration-ms="48979" started-at="2018-10-25T09:52:53Z" finished-at="2018-10-25T09:53:42Z">
      <class name="hackathon.demo.TestClass">
        <test-method status="FAIL" signature="LoginSuccessTC()[pri:0, instance:hackathon.demo.TestClass@47f6473]" name="LoginSuccessTC" duration-ms="31387" started-at="2018-10-25T15:23:05Z" description="Valid login scenerio with authenticate username &amp; password" finished-at="2018-10-25T15:23:37Z">
          <exception class="java.lang.UnsupportedOperationException">
            <message>
              <![CDATA[Cannot convert 'PASSED_ONLY' to com.automation.remarks.video.enums.VideoSaveMode]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.UnsupportedOperationException: Cannot convert 'PASSED_ONLY' to com.automation.remarks.video.enums.VideoSaveMode
	at org.aeonbits.owner.Util.unsupported(Util.java:128)
	at org.aeonbits.owner.Converters.unsupportedConversion(Converters.java:276)
	at org.aeonbits.owner.Converters.access$200(Converters.java:42)
	at org.aeonbits.owner.Converters$4.tryConvert(Converters.java:160)
	at org.aeonbits.owner.Converters.doConvert(Converters.java:268)
	at org.aeonbits.owner.Converters.convert(Converters.java:263)
	at org.aeonbits.owner.PropertiesInvocationHandler.resolveProperty(PropertiesInvocationHandler.java:87)
	at org.aeonbits.owner.PropertiesInvocationHandler.invoke(PropertiesInvocationHandler.java:67)
	at com.sun.proxy.$Proxy9.saveMode(Unknown Source)
	at com.automation.remarks.video.RecordingUtils.doVideoProcessing(RecordingUtils.java:25)
	at com.automation.remarks.testng.VideoListener.onTestSuccess(VideoListener.java:36)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1899)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1879)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:778)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
Caused by: java.lang.IllegalArgumentException: No enum constant com.automation.remarks.video.enums.VideoSaveMode.PASSED_ONLY
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.sun.beans.editors.EnumEditor.setAsText(EnumEditor.java:102)
	at org.aeonbits.owner.Converters$4.tryConvert(Converters.java:157)
	... 31 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.UnsupportedOperationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginSuccessTC -->
        <test-method status="FAIL" signature="LoginFailTC()[pri:0, instance:hackathon.demo.TestClass@47f6473]" name="LoginFailTC" duration-ms="2262" started-at="2018-10-25T15:23:38Z" description="Invalid login scenerio with wrong username &amp; password" finished-at="2018-10-25T15:23:41Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Nielsen Studio] but found [Nielsen Studio » Log in]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Nielsen Studio] but found [Nielsen Studio » Log in]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at hackathon.demo.TestClass.LoginFailTC(TestClass.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginFailTC -->
      </class> <!-- hackathon.demo.TestClass -->
    </test> <!-- Write new post -->
  </suite> <!-- Hackathon-Demo -->
</testng-results>
